# Generated by Django 5.2.3 on 2025-06-30 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
        ("contacts", "0002_remove_contact_created_at_remove_contact_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networknode",
            name="contacts",
        ),
        migrations.AddField(
            model_name="networknode",
            name="contacts",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.contact",
            ),
        ),
    ]
