# Generated by Django 5.2.3 on 2025-07-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_remove_networknode_contacts_networknode_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt_to_supplier",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="level",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
