# Generated by Django 5.2.3 on 2025-07-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0004_transaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
